package org.quelea.services.utils;

public class QueleaPropertyKeys {
    public static final String languageFileKey = "language.file";
    public static final String enableDictKey = "enable.dict";
    public static final String videoTabKey = "video.tab";
    public static final String sceneInfoKey = "scene.info";
    public static final String mainDivposKey = "main.divpos";
    public static final String elevantoClientIdKey = "elevanto.client.id";
    public static final String libraryDivposKey = "library.divpos";
    public static final String preliveDivposKey = "prelive.divpos";
    public static final String canvasDivposKey = "canvas.divpos";
    public static final String previewDivposKey = "preview.divpos";
    public static final String chosenFontsKey = "chosen.fonts";
    public static final String uniformFontSizeKey = "uniform.font.size";
    public static final String showVerseNumbersKey = "show.verse.numbers";
    public static final String noticeBackgroundColourKey = "notice.background.colour";
    public static final String noticePositionKey = "notice.position";
    public static final String noticeSpeedKey = "notice.speed";
    public static final String lastDirectoryKey = "last.directory";
    public static final String lastSchedulefileDirectoryKey = "last.schedulefile.directory";
    public static final String scheduleEmbedMediaKey = "schedule.embed.media";
    public static final String itemThemeOverrideKey = "item.theme.override";
    public static final String globalSongThemeFileKey = "global.song.theme.file";
    public static final String globalBibleThemeFileKey = "global.bible.theme.file";
    public static final String lastVideoDirectoryKey = "last.video.directory";
    public static final String autoplayVidKey = "autoplay.vid";
    public static final String useVlcJavafxRenderingKey = "use.vlc.javafx.rendering";
    public static final String noticeFontSizeKey = "notice.font.size";
    public static final String autoTranslateKey = "auto.translate";
    public static final String maxFontSizeKey = "max.font.size";
    public static final String additionalLineSpacingKey = "additional.line.spacing";
    public static final String thumbnailSizeKey = "thumbnail.size";
    public static final String planningCentrePrevDaysKey = "planning.center.prev.days";
    public static final String showExtraLivePanelToolbarOptionsKey = "show.extra.live.panel.toolbar.options";
    public static final String linkPreviewAndLiveDividers = "link.preview.and.live.dividers";
    public static final String clearLiveOnRemoveKey = "clear.live.on.remove";
    public static final String facebookPageKey = "facebook.page";
    public static final String wikiPageKey = "wiki.page";
    public static final String translationFontSizeOffsetKey = "translation.font.size.offset";
    public static final String stageFontKey = "stage.font";
    public static final String stageTextAlignmentKey = "stage.text.alignment";
    public static final String stageShowChordsKey = "stage.show.chords";
    public static final String phonehomeKey = "phonehome";
    public static final String queleaScheduleExtensionKey = "quelea.schedule.extension";
    public static final String queleaSongpackExtensionKey = "quelea.songpack.extension";
    public static final String controlScreenKey = "control.screen";
    public static final String oneLineModeKey = "one.line.mode";
    public static final String textShadowKey = "text.shadow";
    public static final String projectorScreenKey = "projector.screen";
    public static final String useAutoExtendKey = "use.auto.extend";
    public static final String maxCharsKey = "max.chars";
    public static final String projectorCoordsKey = "projector.coords";
    public static final String projectorModeKey = "projector.mode";
    public static final String stageScreenKey = "stage.screen";
    public static final String stageCoordsKey = "stage.coords";
    public static final String stageModeKey = "stage.mode";
    public static final String minLinesKey = "min.lines";
    public static final String singleMonitorWarningKey = "single.monitor.warning";
    public static final String websiteLocationKey = "website.location";
    public static final String discussLocationKey = "discuss.location";
    public static final String feedbackLocationKey = "feedback.location";
    public static final String checkUpdateKey = "check.update";
    public static final String capitalFirstKey = "capital.first";
    public static final String displaySonginfotextKey = "display.songinfotext";
    public static final String defaultBibleKey = "default.bible";
    public static final String stageChordColorKey = "stage.chord.color";
    public static final String lyricsTextBackgroundEnable = "lyrics.text.background.enable";
    public static final String lyricsTextBackgroundColor = "lyrics.text.background.color";
    public static final String stageLyricsColorKey = "stage.lyrics.color";
    public static final String stageBackgroundColorKey = "stage.background.color";
    public static final String activeSelectionColorKey = "active.selection.color";
    public static final String inactiveSelectionColorKey = "inactive.selection.color";
    public static final String outlineThicknessKey = "outline.thickness";
    public static final String noticeBoxHeightKey = "notice.box.height";
    public static final String noticeBoxSpeedKey = "notice.box.speed";
    public static final String godWordsKey = "god.words";
    public static final String advanceOnLiveKey = "advance.on.live";
    public static final String previewOnImageChangeKey = "preview.on.image.change";
    public static final String useOoKey = "use.oo";
    public static final String ooPathKey = "oo.path";
    public static final String usePpKey = "use.pp";
    public static final String ppPathKey = "pp.path";
    public static final String recPathKey = "rec.path";
    public static final String downloadPathKey = "download.path";
    public static final String convertMp3Key = "convert.mp3";
    public static final String ooOntopKey = "oo.ontop";
    public static final String logoImageLocationKey = "logo.image.location";
    public static final String mobLyricsPortKey = "mob.lyrics.port";
    public static final String useMobLyricsKey = "use.mob.lyrics";
    public static final String planningCenterRefreshToken = "planning.center.refresh.token";
    public static final String useRemoteControlKey = "use.remote.control";
    public static final String remoteControlPortKey = "remote.control.port";
    public static final String remoteControlPasswordKey = "remote.control.password";
    public static final String smallSongTextHPositionKey = "small.song.text.h.position";
    public static final String smallSongTextVPositionKey = "small.song.text.v.position";
    public static final String smallSongTextSizeKey = "small.song.text.size";
    public static final String smallSongTextShowOnSlidesKey = "small.song.text.show.on.slides";
    public static final String smallBibleTextHPositionKey = "small.bible.text.h.position";
    public static final String smallBibleTextVPositionKey = "small.bible.text.v.position";
    public static final String smallBibleTextSizeKey = "small.bible.text.size";
    public static final String showSmallSongTextKey = "show.small.song.text";
    public static final String showSmallBibleTextKey = "show.small.bible.text";
    public static final String maxBibleVersesKey = "max.bible.verses";
    public static final String useMaxBibleCharsKey = "use.max.bible.chars";
    public static final String maxBibleCharsKey = "max.bible.chars";
    public static final String logoFadeDurationKey = "logo.fade.duration";
    public static final String blackFadeDurationKey = "black.fade.duration";
    public static final String clearFadeDurationKey = "clear.fade.duration";
    public static final String translateClientIdKey = "translate.client.id";
    public static final String translateClientSecretKey = "translate.client.secret";
    public static final String clearStageviewWithMainKey = "clear.stageview.with.main";
    public static final String blackStageviewWithMainKey = "black.stageview.with.main";
    public static final String songOverflowKey = "song.overflow";
    public static final String autoDetectPortKey = "auto.detect.port";
    public static final String stageShowClockKey = "stage.show.clock";
    public static final String use24hClockKey = "use.24h.clock";
    public static final String splitBibleVersesKey = "split.bible.verses";
    public static final String lyricWidthBoundKey = "lyric.width.bound";
    public static final String lyricHeightBoundKey = "lyric.height.bound";
    public static final String defaultSongDbUpdateKey = "default.song.db.update";
    public static final String dbSongPreviewKey = "db.song.preview";
    public static final String webRefreshRateKey = "web.refresh.rate";
    public static final String webProxyHostKey = "web.proxy.host";
    public static final String webProxyPortKey = "web.proxy.port";
    public static final String webProxyUserKey = "web.proxy.user";
    public static final String webProxyPasswordKey = "web.proxy.password";
    public static final String churchCcliNumKey = "church.ccli.num";
    public static final String projectorXCoordKey = "projector.x.coord";
    public static final String projectorYCoordKey = "projector.y.coord";
    public static final String projectorWCoordKey = "projector.width.coord";
    public static final String projectorHCoordKey = "projector.height.coord";
    public static final String stageXCoordKey = "stage.x.coord";
    public static final String stageYCoordKey = "stage.y.coord";
    public static final String stageWCoordKey = "stage.width.coord";
    public static final String stageHCoordKey = "stage.height.coord";
    public static final String darkThemeKey = "use.dark.theme";
    public static final String useSlideTransitionKey = "use.fade";
    public static final String slideTransitionInDurationKey = "slide.transition.duration.in";
    public static final String slideTransitionOutDurationKey = "slide.transition.duration.out";
    public static final String useDefaultTranslation = "use.default.translation";
    public static final String defaultTranslationName = "default.translation.name";
    public static final String disableDirectShowForWVC1Key = "disable.directshow.for.wvc1";
    public static final String previewPanelBypass = "preview.panel.bypass";// Bypass
	// ----------------- MIDI section begin -----------------
    public static final String midiEnabled = "midi.enabled";// midi
    public static final String midiInterface = "midi.interface";//midi
    public static final String midiGlobalChannel = "midi.globalChannel";//midi
    public static final String midiAction_Black				=	"midi.Action.Black";  			//  Screen	 	 BlackToggleHandler()
    public static final String midiAction_Clear				=	"midi.Action.Clear";  			//  Screen	 	 ClearToggleHandler()
    public static final String midiAction_Gotoitem			=	"midi.Action.Gotoitem";  		//  Navigate	 GotoItemHandler()
    public static final String midiAction_Next				=	"midi.Action.Next";  			//  Navigate	 NextSlideHandler()
    public static final String midiAction_Nextitem			=	"midi.Action.Nextitem";  		//  Navigate	 NextItemHandler()
    public static final String midiAction_Play				=	"midi.Action.Play";  			//  Multimeda	 PlayHandler()
    public static final String midiAction_Prev				=	"midi.Action.Prev";  			//  Navigate	 PreviousSlideHandler()
    public static final String midiAction_Previtem			=	"midi.Action.Previtem";  		//  Navigate	 PreviousItemHandler()
    public static final String midiAction_Section			=	"midi.Action.Section";  		//  Navigate	 SectionHandler()
    public static final String midiAction_Tlogo				=	"midi.Action.Tlogo";  			//  Screen	 	 LogoToggleHandler()
    public static final String midiAction_TransposeDown1	=	"midi.Action.TransposeDown1";  	//  Edit		 TransposeSongHandler()
    public static final String midiAction_TransposeDown2	=	"midi.Action.TransposeDown2";  	//  Edit		 TransposeSongHandler()
    public static final String midiAction_TransposeDown3	=	"midi.Action.TransposeDown3";  	//  Edit		 TransposeSongHandler()
    public static final String midiAction_TransposeDown4	=	"midi.Action.TransposeDown4";  	//  Edit		 TransposeSongHandler()
    public static final String midiAction_TransposeDown5	=	"midi.Action.TransposeDown5";  	//  Edit		 TransposeSongHandler()
    public static final String midiAction_TransposeDown6	=	"midi.Action.TransposeDown6";  	//  Edit		 TransposeSongHandler()
    public static final String midiAction_TransposeUp0		=	"midi.Action.TransposeUp0";  	//  Edit		 TransposeSongHandler()
    public static final String midiAction_TransposeUp1		=	"midi.Action.TransposeUp1";  	//  Edit		 TransposeSongHandler()
    public static final String midiAction_TransposeUp2		=	"midi.Action.TransposeUp2";  	//  Edit		 TransposeSongHandler()
    public static final String midiAction_TransposeUp3		=	"midi.Action.TransposeUp3";  	//  Edit		 TransposeSongHandler()
    public static final String midiAction_TransposeUp4		=	"midi.Action.TransposeUp4";  	//  Edit		 TransposeSongHandler()
    public static final String midiAction_TransposeUp5		=	"midi.Action.TransposeUp5";  	//  Edit		 TransposeSongHandler()
    public static final String midiAction_TransposeUp6		=	"midi.Action.TransposeUp6";  	//  Edit		 TransposeSongHandler()

    // ----------------- MIDI section end -----------------


}
