name: quelea
version: '2022.0'
base: core18
summary: Church projection
description: |
  Quelea is a free and open source software application that projects
  multimedia content in your church service.
confinement: strict

environment:
    JAVA_HOME: $SNAP/usr/lib/jvm/default-java
    PATH: $SNAP/usr/lib/jvm/default-java/bin:$PATH
    
architectures:
  - build-on: amd64
  - build-on: i386

apps:
  quelea:
    command: sh $SNAP/jar/launch.sh
    plugs: [home, mount-observe, network-control, network, network-bind, x11, wayland, unity7, opengl, optical-drive, alsa, pulseaudio, desktop, desktop-legacy, removable-media, gsettings, account-control]

parts:
  quelea:
    plugin: gradle
    source: Quelea
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
    stage-packages: [default-jre, openjfx, vlc]
    gradle-openjdk-version: "11"
    gradle-options: [--debug, -Dnightly=true, -Dversionsuffix=CI-UNSTABLE, clean, jar, copyToDist]
    gradle-output-dir: 'dist'
