name: quelea
version: '2021.0' 
summary: Church projection
description: |
  Quelea is a free and open source software application that projects
  multimedia content in your church service.

confinement: strict

environment:
    JAVA_HOME: $SNAP/usr/lib/jvm/default-java
    PATH: $SNAP/usr/lib/jvm/default-java/bin:$PATH
    
architectures:
  - build-on: amd64
  - build-on: i386

apps:
  quelea:
    command: sh $SNAP/jar/launch.sh
    plugs: [home, mount-observe, network-control, network, network-bind, x11, wayland, unity7, opengl, optical-drive, alsa, pulseaudio, desktop, desktop-legacy, removable-media, gsettings, account-control]

parts:
  quelea:
    plugin: gradle
    source: Quelea
    stage-packages: [default-jre, openjfx, vlc]
    gradle-options: [-Dnightly=true, -Dversionsuffix=CI-UNSTABLE, clean, jar, copyToDist]
    gradle-output-dir: 'dist'
    after: [desktop-gtk2]
    override-build: |
      printenv
      chmod +x gradlew
      ./gradlew -Dhttp.proxyHost=10.10.10.1 -Dhttp.proxyPort=8222 -Dhttps.proxyHost=10.10.10.1 -Dhttps.proxyPort=8222 -Dnightly=true -Dversionsuffix=CI-UNSTABLE clean jar copyToDist --scan
      ls -l
      cp -r /build/quelea/parts/quelea/build/dist/* /build/quelea/stage
      ls -l /build/quelea/stage


#parts:
#  quelea:
#    plugin: gradle
#    source: Quelea
#    stage-packages: [default-jre, openjfx, vlc]
#    gradle-options: [-Dnightly=true, -Dversionsuffix=CI-UNSTABLE, clean, jar, copyToDist]
#    gradle-output-dir: 'dist'
#    after: [desktop-gtk2]
