name: Update missing labels

on:
  push:
    branches:
      - 'master'

jobs:
  update-labels:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout main source
        uses: actions/checkout@v4
        with:
          path: 'main'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          java-package: 'jdk'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Checkout doc source
        env:
          QBOT_TOKEN: ${{ secrets.QBOT_TOKEN }}
        run: |
          git clone https://quelea-bot:${QBOT_TOKEN}@github.com/quelea-projection/quelea-projection.github.io.git ./doc
      - name: Find missing labels
        run: |
          cd main/Quelea
          chmod +x gradlew
          chmod +x build-install.sh
          ./gradlew -Dnightly=true -Dversionsuffix=CI-UNSTABLE labelcheck
          cd ../..
          cp main/Quelea/dist/missinglabels.js doc/lang/
          cd doc
          git add lang/missinglabels.js
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update missing labels file" || true
          git push
